name: Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Verify build output
        run: |
          echo "Verifying contents of dist directory after build:"
          ls -la ./dist  # List files to confirm they exist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout the target repository
        uses: actions/checkout@v4
        with:
          repository: rgp-paleocapa/receiver  # Change to the target repo's name
          ref: master  # Specify the branch in the target repo you want to push to
          token: ${{ secrets.TARGET_REPO_TOKEN }}  # Use the personal access token for authentication

      - name: Verify dist existence before copying
        run: |
          echo "Checking if dist directory exists in the source repo:"
          ls -la ./dist  # List files in the dist directory
          if [ ! -d "./dist" ]; then
            echo "dist directory does NOT exist."
            exit 1  # Fail the step if dist does not exist
          fi

      - name: Clear target repo and copy built files
        run: |
          echo "Clearing target repo and copying files..."
          rm -rf *  # Clear files in the target repo (if necessary)
          echo "Attempting to copy files from dist to target repo..."
          cp -r ../<your-repo-name>/dist/* ./  # Adjust path based on working directory

      - name: Push to target repository
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy from source repo" || echo "No changes to commit"
          git push origin master  # Push to the appropriate branch
