name: Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
      
      - name: Build project for primary repo
        env:
          VITE_BASE_URL: './'  # Default base URL
        run: |
          echo "Building project with VITE_BASE_URL: $VITE_BASE_URL"
          npm run build

      - name: Check dist contents before upload
        run: ls -la ./dist  # List files to ensure they were built

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

  deploy-to-second-repo:
    name: Deploy to Second Repo
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Checkout the target repository
        uses: actions/checkout@v4 
        with:
          repository: rgp-paleocapa/receiver  # Change to the target repo's name
          ref: master  # Specify the branch in the target repo
          token: ${{ secrets.TARGET_REPO_TOKEN }}  # Use the personal access token
          path: ./receiver

      - name: Clear target repo and prepare for copying files
        run: rm -rf ./receiver/*  # Clear all files in the target repo

      - name: Copy rebuilt files to target repository
        run: |
          if [ -d "./dist" ] && [ "$(ls -A ./dist)" ]; then
            cp -r ./dist/* ./receiver/  # Copy all files and subdirectories from dist to the target repo
          else
            echo "No files found in dist."
            exit 1  # Fail the step if no files were found
          fi
        
      - name: Push to target repository
        run: |
          cd ./receiver  # Change to the target repo directory
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy from source repo with updated VITE_BASE_URL" || echo "No changes to commit"
          git push origin master  # Push to the appropriate branch
