# .github/workflows/deploy-to-second-repo.yml

name: Build and Deploy to Second Repo

on:
  push:
    tags:
      - '*'  # Trigger on any tag push

jobs:
  build-and-deploy:
    name: Build and Deploy to Second Repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
      
      - name: Build project
        env:
          VITE_BASE_URL: './'  # Default base URL
        run: |
          echo "Building project with VITE_BASE_URL: $VITE_BASE_URL"
          npm run build

      - name: Check dist contents before upload
        run: ls -la ./dist  # List files to ensure they were built

      - name: Checkout the target repository
        uses: actions/checkout@v4 
        with:
          repository: rgp-paleocapa/receiver  # Change to the target repo's name
          ref: master  # Specify the branch in the target repo
          token: ${{ secrets.TARGET_REPO_TOKEN }}  # Use the personal access token
          path: ./receiver

      - name: Clear target repo and prepare for copying files
        run: rm -rf ./receiver/*  # Clear all files in the target repo

      - name: Copy rebuilt files to target repository
        run: |
          if [ -d "./dist" ] && [ "$(ls -A ./dist)" ]; then
            cp -r ./dist/* ./receiver/  # Copy all files and subdirectories from dist to the target repo
          else
            echo "No files found in dist."
            exit 1  # Fail the step if no files were found
          fi
        
      - name: Push to target repository
        run: |
          cd ./receiver  # Change to the target repo directory
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy from source repo with updated VITE_BASE_URL" || echo "No changes to commit"
          git push origin master  # Push to the appropriate branch
